# types
- name: "issue: security 🔒"
  description: "This is a security issue/vunerability"
  color: "#B60205"
- name: "issue: bug 🐛"
  description: "Something isn't working"
  color: "#D93F0B"
- name: "issue: feature ⬆️"
  description: "New feature or request"
  color: "#0E8A16"
- name: "issue: good first issue 😎"
  description: "Good for newcomers"
  color: "#0052CC"
- name: "issue: documentation 📃"
  description: "Improvements or additions to documentation"
  color: "#0052CC"

# statuses
- name: "status: backlog 📚"
  description: "The issue is in the backlog and not going to be worked on right now"
  color: "#C5DEF5"
- name: "status: open 📖"
  description: "The issue is in the Todo queue and will be worked on very soon"
  color: "#0052CC"
- name: "status: in progress 🔨"
  description: "Currently being worked on"
  color: "#0E8A16"
- name: "status: in review 👀"
  description: "Currently waiting on passing the CI/CD pipeline and review."
  color: "#5319E7"
- name: "status: duplicate 👥"
  description: "This issue or pull request already exists"
  color: "#D4C5F9"
- name: "status: invalid 🙅‍♂️"
  description: "The issue is incomplete or invalid"
  color: "#D93F0B"
- name: "status: wontfix 🛑"
  description: "This will not be worked on"
  color: "#D93F0B"
- name: "status: blocked 🚫"
  description: "The issue is blocked due to things not under the devs control"
  color: "#FBCA04"
- name: "status: completed ✅"
  description: "The work for the issue is completed and merged"
  color: "#FBCA04"

# support
- name: "support: help wanted 🆘"
  description: "Extra attention is needed"
  color: "#0052CC"
- name: "support: question ❓"
  description: "Further information is requested"
  color: "#0052CC"

# priorities
- name: "priority: urgent 🔴"
  description: "This needs to be worked on urgently"
  color: "#B60205"
- name: "priority: high 🟠"
  description: "This is a high priority issue"
  color: "#D93F0B"
- name: "priority: normal 🟡"
  description: "This is a normal priority issue"
  color: "#FBCA04"
- name: "priority: low ⚪"
  description: "This is a low priority issue"
  color: "#0052CC"
