#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# fix stuff
echo 'formatting and fixing stuff before checks'
npm run lint-staged
npm run fortify
npm run fix:audit

echo 'checking if everything is working and safe'
# check workings
npm run check:quality
npm run check:test
npm run check:coverage
npm run check:license
npm run check:safety
npm run build

echo 'all passed'
